version: "3.9"
services:
  web-server:
        image: nginx
        volumes:
          - ./templates:/etc/nginx/templates
        ports:
          - "5430:5432"
        environment:
          - NGINX_HOST=foobar.com
          - NGINX_PORT=80


  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: "planer_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "myDbPlaner"
    ports:
      - "5431:5432"