create table task (
                      id bigint primary key generated by default as identity ,
                      description varchar(255) not null ,
                      date_of_adding date not null
);

create sequence role_seq start with 1 increment by 1;
create table role (
                      id bigint PRIMARY KEY DEFAULT nextval('role_seq'),
                      role_name varchar(50) DEFAULT 'CONTROLLER',
                      employee_id bigint not null
);

create table employee (
    id bigint primary key generated by default as identity ,
    name varchar(30) not null ,
    surname varchar (30) not null ,
    email varchar(50) not null unique ,
    password varchar(30) not null ,
    local_date date not null,
    role_id bigint not null ,
    foreign key (role_id) references role(id)
);

create sequence working_place_seq start with 1 increment by 1;
create table working_place (
    id bigint PRIMARY KEY DEFAULT nextval('working_place_seq'),
    working_place_name varchar(255) not null,
    employee_id bigint not null,
    task_id bigint not null ,
    foreign key (employee_id) references employee(id),
    foreign key (task_id) references task(id)
);

